---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Watch for any updated table
      servicenow.itsm.incidents:
        instance_url: "https://dev181601.service-now.com"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        query: "active=true^priority=1"

  rules:

    - name: Trigger action on specific event
      condition: event.sys_id is defined
      actions:
        - debug:
            msg: "{{ event.number }} - {{ event.description }}"
