---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:

    - name: Trigger action on specific event
      condition: event.sys_id is defined
      actions:
        - debug:
            msg: "{{ event.number }} - {{ event.description }}"
