---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  sources:
    - name: Watch for any updated table
      servicenow.itsm.records:
        table: sc_request
        interval: 5
  rules:
    - name: EDA - Basic Webhook Testing from EDA COntroller to AAP
          condition: event.meta is defined
          action:
            run_job_template:
              name: 'EDA - Basic Test'
              organization: 'Default'
