---
- name: ServiceNow Incident Remediation
  hosts: all
  sources:
    - name: my_webhook_source
      ansible.eda.event_stream:
        event_stream_name: ServiceNow_Incident_Stream # Match the name from step 2
  rules:
    - name: New High-Priority Incident
      condition: event.payload.priority is defined
      actions:
        - run_job_template:
            name: "Demo Job Template"
            organization: Default
