---
- name: ServiceNow Incident Remediation
  hosts: all
  sources:
    - name: my_webhook_source
      ansible.eda.event_stream:
        event_stream_name: ServiceNow_Incident_Stream # Match the name from step 2
  rules:
    - name: New High-Priority Incident
      condition: event.payload.category == 'inquiry' and event.payload.priority == '5'
      actions:
        - run_job_template:
            name: "Triage High Priority Incident"
            organization: Default
            # Pass necessary event data to the Job Template's extra_vars
            extra_vars:
              incident_sys_id: "{{ event.payload.sys_id }}"
              incident_number: "{{ event.payload.number }}"
